# Generated by Django 6.0.1 on 2026-01-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
